trigger:
- master

jobs:
- job: clang
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      make CC=clang CXX=clang++
    displayName: 'make'

- job: gcc
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      make CC=gcc CXX=g++
    displayName: 'make'
