trigger:
- master

jobs:
- job: clang
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      make CC=clang CXX=clang++
    displayName: 'make'

- job: gcc
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      make CC=gcc CXX=g++
    displayName: 'make'

- job: windows
  strategy:
    matrix:
      x64-release:
        platform: x64
        configuration: Release
      x64-debug:
        platform: x64
        configuration: Debug
      Win32-release:
        platform: Win32
        configuration: Release
      Win32-debug:
        platform: Win32
        configuration: Debug
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: VSBuild@1
    inputs:
      solution: 'vs/vs2015/ducible.sln'
      vsVersion: 'latest'
      platform: $(platform)
      configuration: $(configuration)
      msbuildArgs: '/m'
  - script: |
      runtests.bat vs/vs2015/$(platform)/$(configuration)
    displayName: 'tests'
